version: '3.8'

services:
  test:
    build: .
    command: bash -c "python app/init.py && pytest app/test_main.py"
    volumes:
      - .:/app
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_URL=http://localstack:4566
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_URL=http://localstack:4566
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"